### ISSUE TITLE
Unknown column 'sub_icon_image_service.icon_image_environment_id' in 'on clause'

### ISSUE THREAD

**Issue by Yonas-net** [Icinga/icingadb-web#251]
## Describe the bug
If you press on any `Host` or `Service` group, which has some hosts and/or services in it, the following mysql error will be raised.

```
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'sub_icon_image_service.icon_image_environment_id' in 'on clause'

#0 /usr/local/src/ipl-sql/src/Connection.php(401): PDO->prepare(String)
#1 /usr/local/src/ipl-sql/src/Connection.php(418): ipl\Sql\Connection->prepexec(String, Array)
#2 /usr/local/src/ipl-orm/src/Query.php(639): ipl\Sql\Connection->select(Object(ipl\Sql\Select))
#3 /usr/local/src/ipl-orm/src/ResultSet.php(104): ipl\Orm\Query->yieldResults()
#4 [internal function]: ipl\Orm\ResultSet->yieldTraversable(Object(Generator))
#5 /usr/local/src/ipl-orm/src/ResultSet.php(86): Generator->valid()
#6 /usr/local/src/ipl-orm/src/ResultSet.php(39): ipl\Orm\ResultSet->advance()
#7 /usr/local/src/ipl-orm/src/Query.php(611): ipl\Orm\ResultSet->current()
#8 /usr/local/src/ipl-orm/src/Query.php(505): ipl\Orm\Query->first()
#9 /usr/local/src/ipl-stdlib/src/Properties.php(77): ipl\Orm\Query->ipl\Orm\{closure}(Object(Icinga\Module\Icingadb\Model\Service))
#10 /usr/local/src/ipl-stdlib/src/Properties.php(193): ipl\Orm\Model->getProperty(String)
#11 /usr/share/icingaweb2-modules/icingadb/library/Icingadb/Widget/ItemList/StateListItem.php(34): ipl\Orm\Model->__get(String)
#12 /usr/share/icingaweb2-modules/icingadb/library/Icingadb/Widget/ItemList/BaseServiceListItem.php(49): Icinga\Module\Icingadb\Widget\ItemList\StateListItem->init()
#13 /usr/share/icingaweb2-modules/icingadb/library/Icingadb/Common/BaseListItem.php(42): Icinga\Module\Icingadb\Widget\ItemList\BaseServiceListItem->init()
#14 /usr/share/icingaweb2-modules/icingadb/library/Icingadb/Common/BaseItemList.php(85): Icinga\Module\Icingadb\Common\BaseListItem->__construct(Object(Icinga\Module\Icingadb\Model\Service), Object(Icinga\Module\Icingadb\Widget\ItemList\ServiceList))
#15 /usr/share/icingaweb2-modules/icingadb/library/Icingadb/Widget/ItemList/StateList.php(20): Icinga\Module\Icingadb\Common\BaseItemList->assemble()
#16 /usr/local/src/ipl-html/src/HtmlDocument.php(295): Icinga\Module\Icingadb\Widget\ItemList\StateList->assemble()
#17 /usr/local/src/ipl-html/src/HtmlDocument.php(496): ipl\Html\HtmlDocument->ensureAssembled()
#18 /usr/local/src/ipl-html/src/HtmlDocument.php(339): ipl\Html\HtmlDocument->render()
#19 /usr/local/src/ipl-html/src/BaseHtmlElement.php(255): ipl\Html\HtmlDocument->renderUnwrapped()
#20 /usr/local/src/ipl-html/src/BaseHtmlElement.php(323): ipl\Html\BaseHtmlElement->renderContent()
#21 /usr/local/src/ipl-html/src/HtmlDocument.php(498): ipl\Html\BaseHtmlElement->renderUnwrapped()
#22 /usr/local/src/ipl-html/src/HtmlDocument.php(339): ipl\Html\HtmlDocument->render()
#23 /usr/local/src/ipl-html/src/HtmlDocument.php(498): ipl\Html\HtmlDocument->renderUnwrapped()
#24 /usr/local/src/ipl-web/src/Compat/ViewRenderer.php(56): ipl\Html\HtmlDocument->render()
#25 /icingaweb2/library/vendor/Zend/Controller/Action/Helper/ViewRenderer.php(964): ipl\Web\Compat\ViewRenderer->render()
#26 /icingaweb2/library/vendor/Zend/Controller/Action/HelperBroker.php(272): Zend_Controller_Action_Helper_ViewRenderer->postDispatch()
#27 /usr/share/icingaweb2-modules/icingadb/library/Icingadb/Web/Controller.php(540): Zend_Controller_Action_HelperBroker->notifyPostDispatch()
#28 /icingaweb2/library/Icinga/Web/Controller/Dispatcher.php(76): Icinga\Module\Icingadb\Web\Controller->dispatch(String)
#29 /icingaweb2/library/vendor/Zend/Controller/Front.php(937): Icinga\Web\Controller\Dispatcher->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#30 /icingaweb2/library/Icinga/Application/Web.php(304): Zend_Controller_Front->dispatch(Object(Icinga\Web\Request), Object(Icinga\Web\Response))
#31 /icingaweb2/library/Icinga/Application/webrouter.php(107): Icinga\Application\Web->dispatch()
#32 /icingaweb2/public/index.php(4): require_once(String)
#33 {main}
```

**Comment by Yonas-net** [comment]
```
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'sub_icon_image_host.icon_image_environment_id' in 'on clause'
```
