### ISSUE TITLE
"environment_id should be a resource got string instead" on pgsql database

### ISSUE THREAD

**Issue by mafri27** [Icinga/icingadb-web#576]
## Describe the bug
"environment_id should be a resource got string instead" host-views when using a icingadb pgsql database. If I use a mariadb it is running without error. It do work for a few seconds if I run "icingadb-redis-cli FLUSHDB".

## To Reproduce
Provide a link to a live example, or an unambiguous set of steps to reproduce this issue. Include configuration, logs, etc. to reproduce, if relevant.

```
environment_id should be a resource got string instead

#0 /usr/share/icinga-php/ipl/vendor/ipl/orm/src/Contract/PropertyBehavior.php(63): ipl\Orm\Behavior\Binary->fromDb()
#1 /usr/share/icinga-php/ipl/vendor/ipl/orm/src/Behaviors.php(120): ipl\Orm\Contract\PropertyBehavior->retrieveProperty()
#2 /usr/share/icingaweb2/modules/icingadb/library/Icingadb/Redis/VolatileStateResults.php(131): ipl\Orm\Behaviors->retrieveProperty()
#3 /usr/share/icingaweb2/modules/icingadb/library/Icingadb/Redis/VolatileStateResults.php(79): Icinga\Module\Icingadb\Redis\VolatileStateResults->applyRedisUpdates()
#4 /usr/share/icingaweb2/modules/icingadb/library/Icingadb/Common/BaseItemList.php(87): Icinga\Module\Icingadb\Redis\VolatileStateResults->rewind()
#5 /usr/share/icingaweb2/modules/icingadb/library/Icingadb/Widget/ItemList/StateList.php(23): Icinga\Module\Icingadb\Common\BaseItemList->assemble()
#6 /usr/share/icinga-php/ipl/vendor/ipl/html/src/HtmlDocument.php(295): Icinga\Module\Icingadb\Widget\ItemList\StateList->assemble()
#7 /usr/share/icinga-php/ipl/vendor/ipl/html/src/HtmlDocument.php(497): ipl\Html\HtmlDocument->ensureAssembled()
#8 /usr/share/icinga-php/ipl/vendor/ipl/html/src/HtmlDocument.php(339): ipl\Html\HtmlDocument->render()
#9 /usr/share/icinga-php/ipl/vendor/ipl/html/src/BaseHtmlElement.php(255): ipl\Html\HtmlDocument->renderUnwrapped()
#10 /usr/share/icinga-php/ipl/vendor/ipl/html/src/BaseHtmlElement.php(323): ipl\Html\BaseHtmlElement->renderContent()
#11 /usr/share/icinga-php/ipl/vendor/ipl/html/src/HtmlDocument.php(499): ipl\Html\BaseHtmlElement->renderUnwrapped()
#12 /usr/share/icinga-php/ipl/vendor/ipl/html/src/HtmlDocument.php(339): ipl\Html\HtmlDocument->render()
#13 /usr/share/icinga-php/ipl/vendor/ipl/html/src/HtmlDocument.php(499): ipl\Html\HtmlDocument->renderUnwrapped()
#14 /usr/share/icinga-php/ipl/vendor/ipl/web/src/Compat/ViewRenderer.php(56): ipl\Html\HtmlDocument->render()
#15 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action/Helper/ViewRenderer.php(964): ipl\Web\Compat\ViewRenderer->render()
#16 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action/HelperBroker.php(272): Zend_Controller_Action_Helper_ViewRenderer->postDispatch()
#17 /usr/share/icingaweb2/modules/icingadb/library/Icingadb/Web/Controller.php(491): Zend_Controller_Action_HelperBroker->notifyPostDispatch()
#18 /usr/share/php/Icinga/Web/Controller/Dispatcher.php(76): Icinga\Module\Icingadb\Web\Controller->dispatch()
#19 /usr/share/icingaweb2/library/vendor/Zend/Controller/Front.php(937): Icinga\Web\Controller\Dispatcher->dispatch()
#20 /usr/share/php/Icinga/Application/Web.php(290): Zend_Controller_Front->dispatch()
#21 /usr/share/php/Icinga/Application/webrouter.php(105): Icinga\Application\Web->dispatch()
#22 /usr/share/icingaweb2/public/index.php(4): require_once(String)
#23 {main}
```
## Expected behavior
display host information

## Your Environment

```
$ icingacli --version
Icinga Web 2  2.11.0    
Git Commit    46998464ea9f9e3c2889d98f9fb6df639d972550 
PHP Version   7.4.28    
MODULE       VERSION   
grafana      1.4.2     
icingadb     1.0.0     
lazaroblanc  1.0.0     
monitoring   2.11.0
```

```
$ lsb_release -d
Description:	Debian GNU/Linux 11 (bullseye)
```

```
$ icinga2 --version
icinga2 - The Icinga 2 network monitoring daemon (version: r2.13.4-1)

System information:
  Platform: Debian GNU/Linux
  Platform version: 11 (bullseye)
  Kernel: Linux
  Kernel version: 5.10.0-8-amd64
  Architecture: x86_64

Build information:
  Compiler: GNU 10.2.1
  Build host: runner-hh8q3bz2-project-298-concurrent-0
  OpenSSL version: OpenSSL 1.1.1n  15 Mar 2022
```

**Comment by lippserd** [comment]
Will be fixed asap. Behavior runs on a string since it’s a value from Redis not database.
