### ISSUE TITLE
icingadb is interfering with HostActionsHook and ServiceActionsHook

### ISSUE THREAD

**Issue by geotekberlin** [Icinga/icingadb-web#592]
## Describe the bug
the Host and Service action hooks of the GraphDash module (and possibly other modules as well) are causing a crash in the host and service detail view area of Icinga DB on all hosts and all services. Error message is:

```
Uncaught Error: Call to a member function select() on null in /usr/share/icingaweb2/modules/monitoring/library/Monitoring/Object/MonitoredObject.php:509
Stack trace:
#0 /usr/share/icingaweb2/modules/icingadb/library/Icingadb/Compat/CompatObject.php(98): Icinga\Module\Monitoring\Object\MonitoredObject->fetchHostVariables()
#1 /usr/share/icingaweb2/modules/graphdash/library/Graphdash/ProvidedHook/Monitoring/HostActions.php(15): Icinga\Module\Icingadb\Compat\CompatHost->__get()
#2 /usr/share/icingaweb2/modules/monitoring/library/Monitoring/Hook/HostActionsHook.php(50): Icinga\Module\GraphDash\ProvidedHook\Monitoring\HostActions->getActionsForHost()
#3 /usr/share/icingaweb2/modules/monitoring/library/Monitoring/Hook/ObjectActionsHook.php(21): Icinga\Module\Monitoring\Hook\HostActionsHook->getActionsForObject()
#4 /usr/share/icingaweb2/modules/icingadb/library/Icingadb/Widget/Detail/ObjectDetail.php(158): Icinga\Module\Monitoring\Hook\ObjectActionsHook->getNavigation()
#5 /usr/share/icingaweb2/modules/icingadb/lib
```

The error occurs in the GraphDash module where we call $service->hostVariables and $host->hostVariables. The error occurs only when called via IcingaDB Web, it still works fine in the classic Icingaweb2 detail view.

## Expected behavior
Host and Service Action hooks should work the same way in both Icingaweb2 and IcingaDB web.

## Your Environment
Include as many relevant details about the environment you experienced the problem in.

* Icinga DB Web version 1.0.0
* Icinga Web 2 version 2.11.1
* Web browser: Firefox
* Icinga 2 version r2.13.4-1
* Icinga DB version 1.0.0
* PHP version used 7.4.30
* Debian 11

**Comment by nilmerg** [comment]
Hi, while this is unfortunate (our intent is to be compatible in this regard for a while) you could fix this easily in two ways in your module without waiting for an update on our side:

1) Access the property `_host_graphdash_services` instead, it gives you the value directly and you don't need to call any `fetch*` methods explicitly. This works with the monitoring module and with Icinga DB Web
2) Implement Icinga DB Web's counterpart hooks. Once you do that, they will be preferred and the old hooks are not loaded

No matter what your decision is now, you should go the route of 2) anyway sometime, as with a future update of Icinga DB Web the old monitoring hooks won't be loaded at all anymore.

**Comment by geotekberlin** [comment]
Hi Nilmerg, 
thanks for the tip. Accessing my variables directly as shown in your first suggestion is indeed much simpler and works fine with the monitoring module. However, when called with DB Web, **$service->_host_graphdash_services** returns **null** and **$host->_host_graphdash_services** gives this error:
```
Uncaught Error: Call to protected method Icinga\Module\Icingadb\Compat\CompatHost::fetchRawCustomvars() from context 'Icinga\Module\Icingadb\Compat\CompatService' in /usr/share/icingaweb2/modules/icingadb/library/Icingadb/Compat/CompatObject.php:110
Stack trace:
#0 /usr/share/icingaweb2/modules/graphdash/library/Graphdash/ProvidedHook/Monitoring/ServiceActions.php(18): Icinga\Module\Icingadb\Compat\CompatService->__get()
#1 /usr/share/icingaweb2/modules/monitoring/library/Monitoring/Hook/ServiceActionsHook.php(50): Icinga\Module\GraphDash\ProvidedHook\Monitoring\ServiceActions->getActionsForService()
#2 /usr/share/icingaweb2/modules/monitoring/library/Monitoring/Hook/ObjectActionsHook.php(21): Icinga\Module\Monitoring\Hook\ServiceActionsHook->getActionsForObject()
#3 /usr/share/icingaweb2/modules/icingadb/library/Icingadb/Widget/Detail/ObjectDetail.php(158): Icinga\Module\Monitoring\Hook\ObjectActionsHook->getNavigation()
#4 /usr/share/icingaweb2/modules/icingadb/library/Icingadb/Widget/Detail/ServiceDetail.p
```
I would like to have Graphdash working with both monitoring and DB Web modules so implementing Icinga DB Web's counterpart hooks is not yet an option. 

Any ideas how to make this working in both monitoring and DB Web?

**Comment by nilmerg** [comment]
> However, when called with DB Web, ...

Uhmm :roll_eyes: :neutral_face: 

> so implementing Icinga DB Web's counterpart hooks is not yet an option.

You can of course provide both implementations in parallel.

**Comment by geotekberlin** [comment]
Providing both implementations in parallel was something I was considering, but that would not support the case where both the classic Web and the new DB Web were to be used in parallel, as it is in our case during evaluation of the new GUI. Also I would need to inherit both classes
```
use Icinga\Module\Monitoring\Object\Host;
use Icinga\Module\Monitoring\Object\MonitoredObject;
```
and
```
use Icinga\Module\Icingadb\Hook\ActionsHook\ObjectActionsHook;
use Icinga\Module\Icingadb\Model\Host;
```
but this is not possible because of a naming conflict. I am not very experienced in OO programming, so I have no idea how to work around this problem in an elegant manner.

**Comment by nilmerg** [comment]
Your file structure is already fine with regard to the monitoring hooks:

* library/Graphdash/ProvidedHook/
  * Monitoring/
    * HostActions.php
    * ...

You'd just need to insert the icingadb hooks there:

* library/Graphdash/ProvidedHook/
  * Monitoring/
    * HostActions.php
    * ...
  * Icingadb/
    * HostActions.php
    * ...

The namespace is inferred from the file structure, hence for the monitoring hooks it is `Icinga\Module\GraphDash\ProvidedHook\Monitoring` and for the icingadb hooks it would be `Icinga\Module\GraphDash\ProvidedHook\Icingadb`. Then you can use whatever you need in classes inside these namespaces.

Of course, you need to provide the hooks in the run.php as well:

```
$this->provideHook('icingadb/HostActions');
$this->provideHook('icingadb/ServiceActions');
```

**Comment by geotekberlin** [comment]
Hi nilmerg,
I restructured the GraphDash plugin as you proposed and that seems to be a practical way of serving both Web frontends.  GraphDash still works in monitoring module for both HostActions and ServiceActions, but with IcingaDB Web the HostActions show the following error:

`OutOfBoundsException in /usr/share/icinga-php/ipl/vendor/ipl/stdlib/src/Properties.php:69 with message: Can't access property '_host_graphdash_services'. Property does not exist`

and the ServiceAction throws this error:

`Uncaught Error: Call to protected method Icinga\Module\Icingadb\Compat\CompatHost::fetchRawCustomvars() from context 'Icinga\Module\Icingadb\Compat\CompatService' in /usr/share/icingaweb2/modules/icingadb/library/Icingadb/Compat/CompatObject.php:110`

Is this a bug in IcingaDB Web or am I missing something?

Here is the rewritten plugin: [graphdash_V.1.0_dev.zip](https://github.com/Icinga/icingadb-web/files/9104691/graphdash_V.1.0_dev.zip)
.

**Comment by nilmerg** [comment]
> Can't access property '_host_graphdash_services'.

With Icinga DB Web the access to custom variables is different. You'll get a `Host` model. This and the `Service` model, which the `ServiceActions` hook retrieves, have a property `vars`. This is an associative array which holds all the custom variables. In your case it would be: `$host->vars['graphdash_services']`

> and the ServiceAction throws this error:

Isn't that the same error as previously? To me it seems you didn't provide an implementation for `icingadb/ServiceActions` yet, hence why still the monitoring hook is loaded.

> Here is the rewritten plugin:

Didn't help much. There are no icingadb hooks included.

**Comment by geotekberlin** [comment]
Ah, I wasn't aware that the variables need to be accessed differently with Icingadb. In the Host model  I can now access all icinga variables, but instead of returning my array variable `graphdash_services` I get a hardly usable list of string variables with the literal names of all array contents:

```
var_dump($host->vars) 

array(25) {
  ...
  ["location"]=>string(6) "Berlin"
  ["ping_crta"]=>string(3) "600"
  ["GraphDash_Services[0]"]=>string(20) "cpu-utilization-snmp"
  ["GraphDash_Services[1]"]=>string(11) "memory-snmp"
  ["GraphDash_Services[3]"]=>string(11) "uptime-snmp"
  ["GraphDash_Services[2]"]=>string(12) "storage-snmp"
  ["tcp_port"]=> string(4) "2443"
  ...
}
```
Am I right in assuming that this string conversion of an array is unintended?

Besides I am still struggling with the Service Model. Even though I provided an implementation for `Icingadb/ServiceActions` it seems that the wrong hook is activated. 

By the way I uploaded a wrong (obsolete) zip file yesterday. Sorry for that, here is the correct one:  
[Graphdash_V.1.1.0_dev.zip](https://github.com/Icinga/icingadb-web/files/9113856/Graphdash_V.1.1.0_dev.zip)

**Comment by nilmerg** [comment]
> Am I right in assuming that this string conversion of an array is unintended?

No, it's intended. This is the same format which is used when searching for custom variables with a filter. In your case you could search for `host.vars.graphdash_services[0]=cpu-utilization-snmp` or `host.vars.graphdash_services[*]=memory-snmp` (contains check). To process this in a hook however is indeed not really straightforward.

If you need access to the original custom variable (didn't notice your's is an array), you can access `$host->customvar` instead. Though, that's a query not an array. So to access `graphdash_services` you need to perform this:

```
use ipl\Stdlib\Filter;
// clone avoids unintended side-effects
$customvar = (clone $host->customvar)->filter(Filter::equal('name', 'graphdash_services'))->first();
if ($customvar !== null) {
    $services = json_decode($customvar->value);
}
```


> Besides I am still struggling with the Service Model.

I guess you're not using an IDE of sorts, do you? The `HostActionsHook` and `ServiceActionsHook` of Icinga DB Web require a specific return value. A list of `ipl\Web\Widget\Link` objects.

This is a basic example implementation:
```
use Icinga\Module\Icingadb\Hook\ServiceActionsHook;
use Icinga\Module\Icingadb\Model\Service;
use ipl\Web\Url;
use ipl\Web\Widget\Link;

class ServiceActions extends ServiceActionsHook
{
    public function getActionsForObject(Service $service): array
    {
        return [new Link('test', Url::fromPath('monitoring/list/services'))];
    }
}
```

**Comment by geotekberlin** [comment]
Hello nilmerg,

I finally got the GraphDash module working with either the monitoring or the icingadb module alone or in combination. 
Thanks a lot for your help, I would have given up without your suggestions.

[Graphdash_V.1.1.0_release.zip](https://github.com/Icinga/icingadb-web/files/9128176/Graphdash_V.1.1.0_release.zip)
.

**Comment by nilmerg** [comment]
Nice! Glad I could help :smiley: 

I've also used our discussion here to make a small improvement on how those raw customvars can be accessed: #599

With this, my example can be reduced to this:

```
if (isset($host->customvars['graphdash_services'])) {
    ...
}
```
