### ISSUE TITLE
Uncaught TypeError: abs(): Argument #1 ($num) must be of type int|float, string given in Util/PerfDataFormat.php:120

### ISSUE THREAD

**Issue by jgraichen** [Icinga/icingadb-web#603]
## Describe the bug

A check results with performance data fails to render the check details:

```
Uncaught TypeError: abs(): Argument #1 ($num) must be of type int|float, string given in /usr/share/icingaweb2/modules/icingadb/library/Icingadb/Util/PerfDataFormat.php:120
Stack trace:
#0 /usr/share/icingaweb2/modules/icingadb/library/Icingadb/Util/PerfDataFormat.php(120): abs()
#1 /usr/share/icingaweb2/modules/icingadb/library/Icingadb/Util/PerfData.php(534): Icinga\Module\Icingadb\Util\PerfDataFormat::seconds()
#2 /usr/share/icingaweb2/modules/icingadb/library/Icingadb/Util/PerfData.php(581): Icinga\Module\Icingadb\Util\PerfData->format()
#3 /usr/share/icingaweb2/modules/icingadb/library/Icingadb/Widget/Detail/PerfDataTable.php(86): Icinga\Module\Icingadb\Util\PerfData->toArray()
#4 /usr/share/icinga-php/ipl/vendor/ipl/html/src/HtmlDocument.php(295): Icinga\Module\Icingadb\Widget\Detail\PerfDataTable->assemble()
#5 /usr/share/icinga-php/ipl/vendor/ipl/html/src/HtmlDocument.php(497): ipl\Html\HtmlDocument->ensureAssembled()
#6 /usr/share/icinga-php/ipl/vendor/ipl/html/src/HtmlDocument.php(339): ipl\Html\HtmlDocument->render()
#7 /usr/share/icinga-php/ipl/vendor/ipl/html/src/BaseHtmlElement.php(255): ipl\Html\HtmlDocument->renderUnwrapped()
#8 /usr/share/icinga-php/ipl/vendor/ipl/html/src/BaseHtmlElement.php(323): ipl\Html\BaseHtmlElement->renderContent()
#9 /usr/share/icinga-php/ipl/vendor/ipl/html/src/HtmlDocument.php(499): ipl\Html\BaseHtmlElement->renderUnwrapped()
#10 /usr/share/icinga-php/ipl/vendor/ipl/html/src/HtmlDocument.php(339): ipl\Html\HtmlDocument->render()
#11 /usr/share/icinga-php/ipl/vendor/ipl/html/src/BaseHtmlElement.php(255): ipl\Html\HtmlDocument->renderUnwrapped()
#12 /usr/share/icinga-php/ipl/vendor/ipl/html/src/BaseHtmlElement.php(323): ipl\Html\BaseHtmlElement->renderContent()
#13 /usr/share/icinga-php/ipl/vendor/ipl/html/src/HtmlDocument.php(499): ipl\Html\BaseHtmlElement->renderUnwrapped()
#14 /usr/share/icinga-php/ipl/vendor/ipl/html/src/HtmlDocument.php(339): ipl\Html\HtmlDocument->render()
#15 /usr/share/icinga-php/ipl/vendor/ipl/html/src/BaseHtmlElement.php(255): ipl\Html\HtmlDocument->renderUnwrapped()
#16 /usr/share/icinga-php/ipl/vendor/ipl/html/src/BaseHtmlElement.php(323): ipl\Html\BaseHtmlElement->renderContent()
#17 /usr/share/icinga-php/ipl/vendor/ipl/html/src/HtmlDocument.php(499): ipl\Html\BaseHtmlElement->renderUnwrapped()
#18 /usr/share/icinga-php/ipl/vendor/ipl/html/src/HtmlDocument.php(339): ipl\Html\HtmlDocument->render()
#19 /usr/share/icinga-php/ipl/vendor/ipl/html/src/HtmlDocument.php(499): ipl\Html\HtmlDocument->renderUnwrapped()
#20 /usr/share/icinga-php/ipl/vendor/ipl/web/src/Compat/ViewRenderer.php(56): ipl\Html\HtmlDocument->render()
#21 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action/Helper/ViewRenderer.php(964): ipl\Web\Compat\ViewRenderer->render()
#22 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action/HelperBroker.php(272): Zend_Controller_Action_Helper_ViewRenderer->postDispatch()
#23 /usr/share/icingaweb2/modules/icingadb/library/Icingadb/Web/Controller.php(491): Zend_Controller_Action_HelperBroker->notifyPostDispatch()
#24 /usr/share/php/Icinga/Web/Controller/Dispatcher.php(76): Icinga\Module\Icingadb\Web\Controller->dispatch()
#25 /usr/share/icingaweb2/library/vendor/Zend/Controller/Front.php(937): Icinga\Web\Controller\Dispatcher->dispatch()
#26 /usr/share/php/Icinga/Application/Web.php(290): Zend_Controller_Front->dispatch()
#27 /usr/share/php/Icinga/Application/webrouter.php(105): Icinga\Application\Web->dispatch()
#28 /usr/share/icingaweb2/public/index.php(4): require_once('...')
#29 {main}
thrown
```

## To Reproduce

Our check script returns a performance data with a time field:

```
|time=0.00190139s;;;0,000000
```

When viewing such a check in the web frontend, the above error is shown instead.

![20220721-171739](https://user-images.githubusercontent.com/800848/180252912-26f85e73-6358-41db-a963-8fb1b30f3b7b.png)

## Expected behavior

I would have expected to be shown the check details.

This little change in `PerfDataFormat.php:120` works for me for this check:

```diff
     public static function seconds($value): string
     {
+        $value = (float) $value;
         $absValue = abs($value);
```

The issue seems to be that `$value` is a string, but `abs($value)` in line `120` as well as `abs($value)` in line 138, and `log($value, $base)` in line 145 only accept numerals.

![20220721-173147](https://user-images.githubusercontent.com/800848/180254380-ccdb9fa6-c22c-42f2-a6c9-e39f5ef1edec.png)

## Your Environment

* Icinga DB Web version (System - About): 1.0.0
* Icinga Web 2 version (System - About): 2.11.1
* Web browser: Firefox 102.0.1 (64-bit)
* Icinga 2 version (`icinga2 --version`):
  <details>
    <summary>r2.13.4-1</summary>

    ```
    icinga2 - The Icinga 2 network monitoring daemon (version: r2.13.4-1)
  
    Copyright (c) 2012-2022 Icinga GmbH (https://icinga.com/)
    License GPLv2+: GNU GPL version 2 or later <https://gnu.org/licenses/gpl2.html>
    This is free software: you are free to change and redistribute it.
    There is NO WARRANTY, to the extent permitted by law.
  
    System information:
      Platform: Ubuntu
      Platform version: 22.04 LTS (Jammy Jellyfish)
      Kernel: Linux
      Kernel version: 5.15.0-41-generic
      Architecture: x86_64
  
    Build information:
      Compiler: GNU 11.2.0
      Build host: runner-hh8q3bz2-project-298-concurrent-0
      OpenSSL version: OpenSSL 3.0.2 15 Mar 2022
  
    Application information:
  
    General paths:
      Config directory: /etc/icinga2
      Data directory: /var/lib/icinga2
      Log directory: /var/log/icinga2
      Cache directory: /var/cache/icinga2
      Spool directory: /var/spool/icinga2
      Run directory: /run/icinga2
  
    Old paths (deprecated):
      Installation root: /usr
      Sysconf directory: /etc
      Run directory (base): /run
      Local state directory: /var
  
    Internal paths:
      Package data directory: /usr/share/icinga2
      State path: /var/lib/icinga2/icinga2.state
      Modified attributes path: /var/lib/icinga2/modified-attributes.conf
      Objects path: /var/cache/icinga2/icinga2.debug
      Vars path: /var/cache/icinga2/icinga2.vars
      PID path: /run/icinga2/icinga2.pid
    ```

  </details>
* Icinga DB version (`icingadb --version`):
  <details>
  <summary>v1.0.0</summary>

  ```
  Icinga DB version: v1.0.0

  Build information:
    Go version: go1.18.1 (linux, amd64)
    Git commit: 0061888c404f87158d449d9b3ced82fca269a13b

  System information:
    Platform: Ubuntu
    Platform version: 22.04 LTS (Jammy Jellyfish)
  ``` 

  </details>
* PHP version used (`php --version`):
  <details>
  <summary>8.1.2</summary>

  ```
  PHP 8.1.2 (cli) (built: Jun 13 2022 13:52:54) (NTS)
  Copyright (c) The PHP Group
  Zend Engine v4.1.2, Copyright (c) Zend Technologies
    with Zend OPcache v8.1.2, Copyright (c), by Zend Technologies
  ```

  </details>
* Server operating system and version:
  <details>
  <summary>Ubuntu 22.04</summary>

  ```
  Distributor ID:	Ubuntu
  Description:	Ubuntu 22.04 LTS
  Release:	22.04
  Codename:	jammy
  ```

  </details>

## Additional context

Icinga2, Icinga Web 2, Icinga DB, Icinga DB Web are all installed using the published Ubuntu packages from [packages.icinga.com](https://packages.icinga.com/ubuntu).

PHP is installed from Ubuntu repositories.

**Comment by nilmerg** [comment]
Thanks for reporting!
