### ISSUE TITLE
SQLSTATE[42000]: Syntax error or access violation: 1064 if i use a '.' in access control role name.

### ISSUE THREAD

**Issue by virtualdreams** [Icinga/icingadb-web#742]
## Describe the bug

The following error appears if i use a `Role Name` with a period in name but **not** if i use the `monitoring` module.

`Access Control` -> `Role Name` contains a period like `Ref. 5.4`

When I click on a host or service, I get the following error:
`SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '.` 5`.`4`' at line 1`

Stacktrace:
```
#0 /usr/share/icinga-php/ipl/vendor/ipl/sql/src/Connection.php(401): PDO->prepare()
#1 /usr/share/icinga-php/ipl/vendor/ipl/sql/src/Connection.php(246): ipl\Sql\Connection->prepexec()
#2 /usr/share/icingaweb2/modules/icingadb/library/Icingadb/Authentication/ObjectAuthorization.php(208): ipl\Sql\Connection->fetchOne()
#3 /usr/share/icingaweb2/modules/icingadb/library/Icingadb/Authentication/ObjectAuthorization.php(56): Icinga\Module\Icingadb\Authentication\ObjectAuthorization->loadGrants()
#4 /usr/share/icingaweb2/modules/icingadb/library/Icingadb/Common/Auth.php(61): Icinga\Module\Icingadb\Authentication\ObjectAuthorization::grantsOn()
#5 /usr/share/icingaweb2/modules/icingadb/library/Icingadb/Widget/Detail/QuickActions.php(56): Icinga\Module\Icingadb\Widget\Detail\QuickActions->isGrantedOn()
#6 /usr/share/icinga-php/ipl/vendor/ipl/html/src/HtmlDocument.php(294): Icinga\Module\Icingadb\Widget\Detail\QuickActions->assemble()
#7 /usr/share/icinga-php/ipl/vendor/ipl/html/src/HtmlDocument.php(514): ipl\Html\HtmlDocument->ensureAssembled()
#8 /usr/share/icinga-php/ipl/vendor/ipl/html/src/HtmlDocument.php(338): ipl\Html\HtmlDocument->render()
#9 /usr/share/icinga-php/ipl/vendor/ipl/html/src/BaseHtmlElement.php(297): ipl\Html\HtmlDocument->renderUnwrapped()
#10 /usr/share/icinga-php/ipl/vendor/ipl/html/src/BaseHtmlElement.php(365): ipl\Html\BaseHtmlElement->renderContent()
#11 /usr/share/icinga-php/ipl/vendor/ipl/html/src/HtmlDocument.php(516): ipl\Html\BaseHtmlElement->renderUnwrapped()
#12 /usr/share/icinga-php/ipl/vendor/ipl/html/src/HtmlDocument.php(338): ipl\Html\HtmlDocument->render()
#13 /usr/share/icinga-php/ipl/vendor/ipl/html/src/HtmlDocument.php(516): ipl\Html\HtmlDocument->renderUnwrapped()
#14 /usr/share/icinga-php/ipl/vendor/ipl/web/src/Compat/ViewRenderer.php(56): ipl\Html\HtmlDocument->render()
#15 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action/Helper/ViewRenderer.php(964): ipl\Web\Compat\ViewRenderer->render()
#16 /usr/share/icingaweb2/library/vendor/Zend/Controller/Action/HelperBroker.php(272): Zend_Controller_Action_Helper_ViewRenderer->postDispatch()
#17 /usr/share/icingaweb2/modules/icingadb/library/Icingadb/Web/Controller.php(506): Zend_Controller_Action_HelperBroker->notifyPostDispatch()
#18 /usr/share/php/Icinga/Web/Controller/Dispatcher.php(76): Icinga\Module\Icingadb\Web\Controller->dispatch()
#19 /usr/share/icingaweb2/library/vendor/Zend/Controller/Front.php(937): Icinga\Web\Controller\Dispatcher->dispatch()
#20 /usr/share/php/Icinga/Application/Web.php(290): Zend_Controller_Front->dispatch()
#21 /usr/share/php/Icinga/Application/webrouter.php(105): Icinga\Application\Web->dispatch()
#22 /usr/share/icingaweb2/public/index.php(4): require_once(String)
#23 {main}
```

sql_error_log:
```
2023-04-14 10:07:48 icingadb[icingadb] @ localhost [] ERROR 1064: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '.` 5`.`4`' at line 1 : 
SELECT (SELECT (1) FROM host WHERE ( EXISTS (SELECT (1) FROM customvar_flat sub_customvar_flat INNER JOIN host_customvar sub_customvar_flat_host_customvar ON sub_customvar_flat_host_customvar.customvar_id = sub_customvar_flat.customvar_id INNER JOIN host sub_customvar_flat_host ON sub_customvar_flat_host.id = sub_customvar_flat_host_customvar.host_id WHERE (sub_customvar_flat_host.id = host.id) AND ((sub_customvar_flat.flatname = ?) AND (sub_customvar_flat.flatvalue = ?)))) AND (host.id = ?) LIMIT 1) AS `Laenderserver`, (SELECT (1) FROM host WHERE ( EXISTS (SELECT (1) FROM customvar_flat sub_customvar_flat INNER JOIN host_customvar sub_customvar_flat_host_customvar ON sub_customvar_flat_host_customvar.customvar_id = sub_customvar_flat.customvar_id INNER JOIN host sub_customvar_flat_host
```

## To Reproduce

If i rename the `Role Name` to `Referat 5 4` it works in `monitoring` and `icingadb` module.

## Your Environment
Include as many relevant details about the environment you experienced the problem in.

* Icinga DB Web version (System - About): 1.0.2
* Icinga Web 2 version (System - About): 2.11.4
* Web browser: Firefox 112
* Icinga 2 version (`icinga2 --version`): 2.13.7
* Icinga DB version (`icingadb --version`): 1.1.0
* PHP version used (`php --version`): 7.4.33
* Server operating system and version: Debian 11

**Comment by sukhwinder33445** [comment]
I can reproduce this by defining an object restriction.
